# Generated by Django 5.2.3 on 2025-06-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('amount', 'Amount')], default='equal', max_length=20),
        ),
    ]
