# Generated by Django 5.2.3 on 2025-06-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bill_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
